### ISSUE TITLE
arangojs version

### ISSUE THREAD

**Issue by AmmarMohamed** [arangodb/arangojs#182]
https://github.com/A5hpat/nodeArangoWebApp.git
I use this project and using arangojs version ^4.3.0 and return error
////////////////////////////////////////////////////////////////////////////////////////////////////
↓↓↓↓ Getting User lists ↓↓↓↓
{ message: 'db.database is not a function',
error: [TypeError: db.database is not a function] }
GET /users 500 7.306 ms - 2144
/////////////////////////////////////////////////////////////////////////////////////////////////////

But when i use arangojs version number (3.8.4) the project is run successfully what is wrong ??? what can i chenge in the code to use the verion latest version (4.3.0) .

pleas help me @pluma

**Comment by AmmarMohamed** [comment]
@pluma

**Comment by pluma** [comment]
@AmmarMohamed That is correct. The project you linked to explicitly uses arangojs 3, which has a slightly different API from arangojs 4.

Here is the documentation for the last 3.x release: https://github.com/arangodb/arangojs/tree/v3.9.1

Note that `db.database` has been replaced with `db.useDatabase`, which no longer returns a promise but instead changes which database the `db` object refers to. If you need two database objects, just create a second one and call `useDatabase` on only one of them.

**Comment by AmmarMohamed** [comment]
what is the main different between arangojs 3 and arango js 4

**Comment by AmmarMohamed** [comment]
i mean the feature between them

**Comment by pluma** [comment]
The arangojs driver follows semantic versioning, i.e. the major version does not indicate the addition of significant features but that the API changes in backwards-incompatible ways.

Specifically the 4.0 release changed a lot of methods so they no longer fetch the meta information resources (like collections and graphs) allowing those methods to be synchronous (at the expense of no longer guaranteeing the thing you refer already exists).

For example `db.collection('foo')` now synchronously returns an empty object representing the `foo` collection API. In 3.x it would first make an asnychronous roundtrip to the server to determine whether the collection exists and if it didn't either fail or try to create the collection, before resolving to the same object (but with the meta information of the collection mixed into it). In order to perform the same existence check and fetch the metainformation you now need to explicitly call `.get()` on the collection object.

You can find more complete changelogs per version at https://github.com/arangodb/arangojs/releases
