### ISSUE TITLE
NativeScript Integration error

### ISSUE THREAD

**Issue by Terristen** [arangodb/arangojs#208]
Attempting to add to a NativeScript application, throws error when require("arangojs") is added to the project.

I'm posting here as the error is firing from arangojs, but the err could stem from some aspect of NativeScript. If there's a workaround/fix/something-im-doing-wrong, I appreciate someone pointing me in the right direction. Thanks. I know NativeScript is an edge-case, but maybe someone's tried this before?

Exception as listed in the emulator (using Genymotion Android Image):
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.myapp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: inherits is not a function
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'/data/data/org.nativescript.myapp/files/app/tns_modules/http-errors/index.js', line: 110, column: 3
	Frame: function:'', file:'/data/data/org.nativescript.myapp/files/app/tns_modules/http-errors/index.js', line: 72, column: 7
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.myapp/files/app/tns_modules/arangojs/lib/connection.js', line: 19, column: 19
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.myapp/files/app/tns_modules/arangojs/lib/database.js', line: 19, column: 19
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.native
```

**Comment by pluma** [comment]
Going by the error it seems the code that is blowing up is the [http-errors](https://www.npmjs.com/package/http-errors) module, which is a dependency of arangojs. The underlying problem seems to be with the [inherits](https://www.npmjs.com/package/inherits) module but I recall having seen the exact same problem before with http-errors, so that might still be the best place to look.

I suggest also reporting this error at the [http-errors repo](https://github.com/jshttp/http-errors) as it's likely not a problem that is specific to arangojs. There's not much I can do myself.

**Comment by Terristen** [comment]
Thanks pluma. I'll start looking in that direction.
