### ISSUE TITLE
Typo :  "/_apiimport"

### ISSUE THREAD

**Issue by ctmakro** [arangodb/arangojs#234]
You guys do have tests, don't you
```
blahblahblah
body: 
      { error: true,
        code: 404,
        errorNum: 404,
        errorMessage: 'unknown path \'/_apiimport?type=auto&collection=posts\'' },
```

Win7 64bit
Fixed after downgraded to arangojs@4.2.1

**Comment by jsteemann** [comment]
Seems like the path prefix is wrong: should be `/_api/import` instead of `/_apiimport`.

**Comment by KOBA789** [comment]
Does this patch #233 fix the issue?

**Comment by Simran-B** [comment]
I doubt that. But might the same line of code be responsible and need to be
changed to this?

`this._api = this._connection.route('/_api/')`

**Comment by jsteemann** [comment]
Note that I also fixed this one:
https://github.com/arangodb/arangojs/commit/152cf84847befb156f8be2c8d73792686c75de72

However, I am unable to create a new driver release. @pluma has been notified to do that.

**Comment by pluma** [comment]
I've made a bugfix release with these changes.

@ctmakro as you can see from the README we do have some test coverage though there are quite a few known blind spots. I would like to apologize that the latest minor release (4.5) was not quite up to the usual standard however and that there has been a bit of a delay in handling the issues introduced in that version.

We had to write and publish the release within less than a day for internal reasons and it seems some of the optimizations were not quite as straightforward as they seemed to be (resulting in string concatenation problems for less covered functionality like the one you encountered). I was unavailable for the days after the release, so I couldn't address the issues myself (because npm currently only offers organizations for commercial accounts we previously did not have other maintainers authorized to publish releases). 

However if you do encounter other problems with this minor release (4.5), the only difference between it and the one immediately preceding (4.4) it are the optimizations. You can install that version of arangojs using `npm install arangojs@4.4` instead of the usual `npm install arangojs`.

**Comment by ctmakro** [comment]
@pluma I found this bug several days ago when exporting from MySQL then importing to ArangoDB (yes we changed our entire infrastructure, now based on Arango). After initial deployment of our project with `npm install` on our production server, the problem occured.

Sorry for my language, not really trying to blame anyone.
