### ISSUE TITLE
disconnect event

### ISSUE THREAD

**Issue by mikestaub** [arangodb/arangojs#237]
It would be very useful if this library provided a way to handle lost connections to arango. This way we could gracefully attempt to reconnect. Would it be possible to add something like the following (taken from mongodb for example)

```
var MongoClient = require('mongodb').MongoClient;

MongoClient.connect('mongodb://localhost:27017/example', function(err, db) {
  db.on('close', function () {
    console.log('Error...close');
  });
});
```

**Comment by pluma** [comment]
Unlike MongoDB ArangoDB uses HTTP instead of a custom protocol. Since HTTP is not bidirectional or persistent there is no need to maintain open connections indefinitely. ArangoDB does support keep-alive but any lost connections are automatically re-opened the next time they are needed. So it shouldn't be necessary to react to keep-alive connections timing out.

Do you have a specific use case in mind? Have you run into a specific problem with arangojs?

**Comment by mikestaub** [comment]
I am using the DC/OS package and I would like a way to gracefully fallback to the second coordinator when the first one goes down.

After the coordinator goes down, the connection uri is invalid and I have to reinitialize the arangoDB client completely to pick up the new coordinator uri. This just seemed like a lot of work, I was hoping there was an easier way to handle a lost connection. But I guess there is not as like you said arangoDB uses HTTP.

**Comment by fceller** [comment]
@mikestaub the new ArangoDB 3.0 contains a HAproxy, which will automatically switch the between the coordinators.

**Comment by mikestaub** [comment]
Great! :)
