### ISSUE TITLE
problem with createDatabase while BasicAuth is enable

### ISSUE THREAD

**Issue by Geeknux** [arangodb/arangojs#28]
Hi,
i have problem with this driver, while basic Authentication in Arangodb is enabled, createDB doesn't work properly, it creates Database but none of users can access to it. can you solve this?

**Comment by jsteemann** [comment]
In order to create any authorized user, the driver will need to pass a `users` attribute when sending the createDatabase request to the server (as shown in section **create Database** in https://docs.arangodb.com/HttpDatabase/DatabaseManagement.html). It currently does not do this.

If no user is passed into a createDatabase call, the server will create the database with a default user named `root` and empty password. It does so because otherwise the new database would be completely inaccessible (i.e. useless).

The best option is therefore to allow clients to pass the user data into the createDatabase function in the driver.

**Comment by jsteemann** [comment]
@pluma, can you have a look at this? Thanks.

**Comment by Geeknux** [comment]
i change the createdatabase function myself, like this. and my problem got solved, if it's ok i can send you a pull request.

  createDatabase: function createDatabase(databaseName, authInfo, cb) {
    if (typeof authInfo === 'function') {
      cb = authInfo;
      authInfo = undefined;
    }

    if (authInfo !== undefined) {
      if (authInfo.username  && authInfo.passwd) {
        authInfo['active'] = true;
      } else {
        authInfo = undefined;
      }      
    }

    var _promisify11 = promisify(cb);

    var promise = _promisify11.promise;
    var callback = _promisify11.callback;

    var self = this;
    
    if (authInfo === undefined) {
      self._api.post('database', { name: databaseName }, function (err, res) {
        if (err) callback(err);else {
          callback(null, new Database(extend({}, self._connection.config, { databaseName: databaseName })));
        }
      });      
    } else {
      
      console.log(authInfo);
      self._api.post('database', { name: databaseName, users: [authInfo] }, function (err, res) {
        if (err) callback(err);else {
          callback(null, new Database(extend({}, self._connection.config, { databaseName: databaseName })));
        }
      });
    }

**Comment by jsteemann** [comment]
Thanks a lot!
I'll leave it up to @pluma, the driver's maintainer to decide how to go on with this.

**Comment by pluma** [comment]
I'll look into this when I'm on site tomorrow.

**Comment by pluma** [comment]
I've added the `users` option from the HTTP API to the method. You can now pass in an array of user objects as expected, which solves the issue.

The change has been published on NPM as 3.5.1.
