### ISSUE TITLE
Droping a Graph

### ISSUE THREAD

**Issue by XescuGC** [arangodb/arangojs#30]
I have found an error when trying to drop a graph. The code is the following:
```
  db.dropGraph(graphName)
```
The stack of the error is the following:
```
Unhandled rejection ArangoError: TypeError: Cannot read property '_properties' of undefined
  at new ArangoError (/path/to/project/node_modules/arangojs/lib/error.js:10:13)
  at Request._callback (/path/to/project/node_modules/arangojs/lib/connection.js:78:81)
  at Request.self.callback (/path/to/project/node_modules/arangojs/node_modules/request/request.js:368:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/path/to/project/node_modules/arangojs/node_modules/request/request.js:1219:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/path/to/project/node_modules/arangojs/node_modules/request/request.js:1167:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickCallback (node.js:419:13)
```
The error behaves as following:
* The error is raised even if the collection exists or not
* Even though the error the Graph is droped

**Comment by pluma** [comment]
Thanks for spotting this one.

**Comment by XescuGC** [comment]
Forget this one, is related to the #31, i've just tested it right now

**Comment by XescuGC** [comment]
Could you have a look at it? I still have this error, the behavior is the same as commented on the issue. I thought it works because i had in a catch the code because it deletes the Graph anyway.

More trace:
```
{ 
        error: true,
        code: 400,
        errorNum: 17,
        errorMessage: 'TypeError: Cannot read property \'_properties\' of undefined' 
}
```

**Comment by pluma** [comment]
That's a server-side error message. Can you confirm that this doesn't happen if you use the HTTP API directly?

i.e. `curl -X DELETE http://localhost:8529/_api/gharial/graphName`

**Comment by XescuGC** [comment]
Hi @pluma,

Sorry for making you wait, i've tried the CURL and this is the result I get:

  * First i've checked that the Graph was created (via web)
  * Then I execute the CURL: `curl -X DELETE http://localhost:8529/_api/gharial/recipesGraph`
  * Answer: `{"error":true,"code":404,"errorNum":1924,"errorMessage":"graph not found"}` i've checked the name and it's the correct one.
  * I go to check the Graph to the web with a wierd web error because when i open it, it turns the screen in black with 11 alerts saying: "Sorry your graph seems to be empty"
  * And some times the graph opens normally.
  * it's a 'big' (more or less i don't know jeje) graph, 117k edges and 11k + 4k nodes

![arangodb_web_interface_-_vimperator](https://cloud.githubusercontent.com/assets/1532900/9430532/22546dc8-49fa-11e5-8271-924413a68e38.png)

You can reach me via Gitter if you want :smile:

**Comment by pluma** [comment]
That appears to be a bug in the REST API of ArangoDB itself then. Could you please open an issue on the arangodb issue tracker and cross-reference this issue? That will help make sure the right people see it.
Thank you for the patience.
On 24 Aug 2015 12:51 am, Francesc Gil <notifications@github.com> wrote:Hi @pluma,

Sorry for making you wait, i've tried the CURL and this is the result I get:

First i've checked that the Graph was created (via web)Then I execute the CURL: curl -X DELETE http://localhost:8529/_api/gharial/recipesGraph
Answer: {"error":true,"code":404,"errorNum":1924,"errorMessage":"graph not found"} i've checked the name and it's the correct one.I go to check the Graph to the web with a wierd web error because when i open it, it turns the screen in black with 11 alerts saying: "Sorry your graph seems to be empty"And some times the graph opens normally.it's a 'big' (more or less i don't know jeje) graph, 117k edges and 11k + 4k nodes



You can reach me via Gitter if you want
