### ISSUE TITLE
Support for Collection.upsert?

### ISSUE THREAD

**Issue by niranjans** [arangodb/arangojs#325]
Just a quick question, is there support for Collection.upsert or is running an AQL query the only way for Upsert?

**Comment by pluma** [comment]
Upsert is only available via AQL. There is no `collection.upsert` method.

**Comment by mrksbnch** [comment]
I know this is an old issue but are there any plans to add a `collection.upsert` method in the future? Or is there a specific reason why this isn't implemented, yet?

**Comment by pluma** [comment]
@mrksbnch The driver wraps the HTTP API. Upsert is currently only available via AQL, not the HTTP API.

If you want to see an upsert method outside AQL you should probably file an issue with [ArangoDB](/arangodb/arangodb/issues) but I think there are currently no plans to implement this.

**Comment by coldcoff** [comment]
Note that depending on your usecase you might suceed with a "pseudo upsert" without AQL when using the "import" API: https://docs.arangodb.com/3.1/HTTP/BulkImports/ using the "import" HTTP API.
Here is a "onDuplicate" parameter.

**Comment by fceller** [comment]
One of the major issues with upsert is that you access to old data. This can easily be handled in AQL, but not in a simple call to an upsert endpoint. Therefore we decided against such a call and instead implemented it in AQL.

**Comment by mrksbnch** [comment]
@fceller I see the point that you mentioned with `upsert` but I think a slightly more "complex" `upsert` endpoint (with some parameters) could still be implemented to simplify a "create or update" functionality. I might be the only one with this use case but I'm missing an easy way to create/save or update documents (depending if the document already exists). The current workarounds are either:

- First check if document exist and then create or update it
- Use the bulk import with the 'onDuplicate' parameter (which is something that I only found because @coldcoff luckily mentioned it in this issue)

I know that you can do a little more with the AQL upsert and this should probably be in a separate issue but a simple 'onDuplicate' parameter for `documentCollection.save` could probably be a first step to solve most or at least some "upsert" use cases (not the complex ones of course). But again, I'm not sure about the use cases of others but I'm pretty sure that "create or update" is not uncommon as a database action.

**Comment by XBeg9** [comment]
@mrksbnch +1

**Comment by RienNeVaPlus** [comment]
I thought I'd share my implementation of a custom `collection.bulkUpsert` using AQL's [UPSERT](https://www.arangodb.com/docs/stable/aql/operations-upsert.html) and [MERGE](https://www.arangodb.com/docs/stable/aql/functions-document.html#merge) functions, as it might be handy to some who are having the same issue.

<kbd>TypeScript</kbd>
<sub>Source: [collection.bulkUpsert.ts Gist](https://gist.github.com/RienNeVaPlus/942cf74369037ad8f00e5d176ffe1773)</sub>

````typescript
/**
 * Upserts (merges) the content of the documents with the given documents and
 * optionally returns an array containing the documents’ metadata.
 *
 * @param {string|ArangoDB.Collection} collection - collection to use
 * @param {Document[]} documents - list of documents to upsert
 * @param opts? - optionally aggregate a result {inserted:number,updated:number}
 *  also see https://www.arangodb.com/docs/stable/aql/operations-upsert.html
 */
export async function bulkUpsert(
	collection: string | DocumentCollection,
	documents: Array<ArangoDB.DocumentData>,
	{ aggregate, ...upsertOptions }: {
		ignoreRevs?: boolean,
		exclusive?: boolean,
		aggregate?: boolean
	} = {}
): Promise<{inserted:number,updated:number} | true>
{
	return await (
		await db.query({
			query:  'FOR doc IN @documents'
			      + ' UPSERT { _key: doc._key } INSERT doc UPDATE MERGE(OLD, doc)'
			      + ' IN '+(typeof collection === 'string' ? collection : collection.name)
			      + ' OPTIONS '+JSON.stringify(upsertOptions)
			      + (aggregate ?
			        ' COLLECT AGGREGATE inserted = SUM(OLD ? 0 : 1), updated = SUM(OLD ? 1 : 0)'
			      + ' RETURN {inserted,updated}' :
			        ' RETURN true'),
			bindVars: {documents}
		})
	).next();
}
````

**Comment by rjhilgefort** [comment]
bump +1

**Comment by pluma** [comment]
FYI the `collection.save` method supports an `overwriteMode` option that determines what will happen if the document already exists (replace or update). This will be explicitly supported in arangojs 7.

**Comment by rjhilgefort** [comment]
Nice, thanks for the heads up!
