### ISSUE TITLE
Incomplete repo when installing arangojs via github within package.json

### ISSUE THREAD

**Issue by janwo** [arangodb/arangojs#337]
When i am trying to pull the master repo via npm, I only get those files that are referenced within the files array in `arangodb/arangojs/package.json`:
- arangojs.d.ts
- LICENSE
- package.json
- README.md

There is no way to run `npm install` properly then as all needed source files are missing. Do you guys plan to update the npm version, so I can pull the built files right away?

```
depedencies: {
    "arangojs": "arangodb/arangojs"
}
```

**Comment by pluma** [comment]
Yeah, we'll sort that out. There's a longstanding bug with `npm publish` that causes files to be randomly dropped from the bundle. Thanks for bringing this to our attention.

**Comment by pluma** [comment]
I think I misunderstood the issue.

It's not possible to install the package from GitHub with npm because npm only fetches the files specified in the package.json, some of which are build artefacts.

If you want to install from GitHub you need to clone the repository and run the `dist` script. You can't just npm install this library from GitHub.

Either way, it's no longer an issue -- the npm version has been updated to the current master.
