### ISSUE TITLE
NodeJS 6 and 7 support

### ISSUE THREAD

**Issue by reidlai** [arangodb/arangojs#347]
When will ArangoJS support NodeJS 6 and  7?

**Comment by pluma** [comment]
ArangoJS is always tested agains the latest public release, which is currently Node 7, e.g.:

https://travis-ci.org/arangodb/arangojs/jobs/173202649

So to answer your question: it already supports Node 7 and should work fine in Node 6.

I suppose the wording in the README is a bit unclear because it emphasises the LTS (which was 4.x at the time) and doesn't mention any other versions. I'll adjust that to make it clearer.

**Comment by pluma** [comment]
The 3.1 builds are currently failing because the travis version of ArangoDB 3.1 hasn't been published yet. This does not affect the compatibility -- the tests are passing with 3.0 and the development build (which is currently equivalent to 3.1).
