### ISSUE TITLE
graph.vertexCollection.save() does not return a doc but an http response

### ISSUE THREAD

**Issue by sylvainlap** [arangodb/arangojs#354]
According to https://github.com/arangodb/arangojs#graphvertexcollectionsave, vertexCollection.save() should return a doc. However, it returns an object with 3 attributes: code, error & vertex.

Proof is in this screenshot (see the console, with is the log of "result").

![2016-11-15 1](https://cloud.githubusercontent.com/assets/8457604/20312451/d71fcd86-ab53-11e6-8e2e-76f7f4c6a9d2.png)

**Comment by pluma** [comment]
Oops, thanks for catching that.

**Comment by pluma** [comment]
The problem seems to be that the client logic is the same as with the regular collection API but the actual HTTP API behaves differently. Not sure what the point of that is (the graph API was implemented later and in JS so it's probably unintentional), but we should probably unify the behaviour in the client.

**Comment by sylvainlap** [comment]
Shouldn't be the REST API to be unified ?

**Comment by pluma** [comment]
Maybe, but that wouldn't be a backwards compatible change, so it probably would not happen before ArangoDB 4.0.

**Comment by janwo** [comment]
I have the same problem right now. Will this getting fixed soon? Or is there a workaround as long as this behavior persists. Docs say that it should actually return the document itself.

**Comment by pluma** [comment]
This has been addressed in the development version and will be fixed in the upcoming arangojs 6.0.0.
