### ISSUE TITLE
Typescript definitions: Outdated?

### ISSUE THREAD

**Issue by Aranir** [arangodb/arangojs#391]
When I was toying with arrangodb and trying to use the typescript definitions on a node applications I had a few issues.

Are the definitions outdated?

as example the definition of the `save` method on the EdgeCollection is as follows:

```
        save(data: string, fromId?: string, toId?: string): Promise<any>;
```

Where the `data` property is a string.

From the API documentation, the same method is documented as:

```
async edgeCollection.save(data, [fromId, toId]): Object

-> data: Object
```

Why is the data property typed as string whereas in the js version it's supposed to be an Object?

**Comment by pluma** [comment]
The TypeScript definitions aren't officially maintained and were supplied by the community, so it's entirely possible they may be inaccurate. I don't think the methods changed since the last PR to the definitions, though, so it must be a flaw in the original definitions.

If you want to help us, you could check to see which definitions seem inaccurate and contribute a PR to fix them.

**Comment by djoodle** [comment]
Would it be possible to delete the typings if they aren't going to be maintained with the source?

I cant work out how you should import arangojs to make the connection or the aql tag via the typings... it doesn't seem to line up with:

import arangojs, {Database, aql} from 'arangojs';

**Comment by Phaze1D** [comment]
I think it would be best if you guys remove the typings file because it gets really annoying when it isn't up to date for typescript users, and it's ok if you guys don't want to officially support typescript. If somebody does want to contribute by adding types they should add them to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo and not this repo, so that typescript users won't be forced to use outdated types.

**Comment by pluma** [comment]
@mpv1989 Can you look into this? I think I'm +1 on removing the d.ts file from this repo to eliminate the noise for now. We should probably leave it to the community to maintain the typings via DefinitelyTyped unless we start dogfooding TypeScript eventually.
