### ISSUE TITLE
Don't check for window to detect browsers

### ISSUE THREAD

**Issue by pluma** [arangodb/arangojs#410]
This check is unreliable and causes arangojs to break when the global window object is present on the server, e.g. when using jest.

The browser detection should instead happen at compile time when feature detection is not an option.

**Comment by sleepycat** [comment]
Just to add a little context in the hopes of making this a little more search-able:

```javascript
    it('can talk to arangodb', async () => {

      let db = arangojs({
	url: `http://username:password@127.0.0.1:8529`,
	databaseName: 'mydb'
      })

      async function getPersonByName (name) {
	let query = aql`
	  FOR person IN persons
	    FILTER person.name == ${ name }
	      RETURN person
	`
	let results = await db.query(query)
	return await results.next()
      }
      let person = await getPersonByName('Eve')
      expect(person.name).toEqual("Eve")
    })
```

Running that test with Jest fails with the error `ArangoError: query is empty`.
This is because [Jest creates a `window` object](https://egghead.io/lessons/javascript-test-javascript-with-jest) (2:07) by default.

Adding the following jest configuration to your package.json tells Jest not to create the `window` object, at which point Arangojs sets the Content-Length properly and the test passes: 
```javascript
  "jest" : {
    "testEnvironment" : "node"
  }
```
