### ISSUE TITLE
Connection management in express

### ISSUE THREAD

**Issue by samuelgoldenbaum** [arangodb/arangojs#43]
What is the preferred method of managing connections in express.js? one connection at startup? Looking through the code, I couldn't see any connection pool management, but may have missed it.

**Comment by pluma** [comment]
arangojs manages the connection using an HTTP agent. By default it creates the agent for you and sets the maximum number of sockets it can use. You can either modify the options it uses to create the agent or create an agent yourself.

You can share an HTTP agent between multiple clients but arangojs internally creates an additional queue to prevent the agent from being flooded when a large number of new requests are made (this sounds inefficient but has drastically improved the performance).

Personally, I would just create one `Database` (the class exported by arangojs) instance at startup and inject it into your express app.

If you don't find the default configuration to work for you, you should try adjusting the `maxSockets` setting in `agentOptions` and make sure it aligns with the number of V8 threads of your ArangoDB installation.

The [recently published benchmarks](https://www.arangodb.com/2015/06/performance-comparison-between-arangodb-mongodb-neo4j-and-orientdb/) were performed using arangojs with the default settings (except for `maxSockets`), so that should give you an idea of the general characteristics.
