### ISSUE TITLE
why i need this driver? graphql does not work just with a js graphl library?

### ISSUE THREAD

**Issue by webmobiles** [arangodb/arangojs#465]
This is not a bug, but  i have not found information in another site

i'm lost about graphql and arangodb concepts.
Why need to learn aql , or cypher,etc,  i'd like to have a graphql database , which is enought to use graphl to manage crud ...

thanks for get me clear

**Comment by pluma** [comment]
Let me try to break this down:

**ArangoDB** is a database with an HTTP API. The arangojs driver lets you talk to ArangoDB from Node.js with a slightly more natural JavaScript API that abstracts some of the details of the underlying HTTP communication (e.g. URLs, HTTP methods, etc).

For performing complex queries that involve filters, aggregation, traversals or subqueries/joins, ArangoDB provides **AQL**, which is a language similar to SQL but better suited to the database's multi-model nature (whereas SQL was created for querying strictly tabular data).

Despite its name, **GraphQL** is neither a query language nor does it support graph queries. GraphQL is more like XML in that it defines a syntax and structure but leaves the semantics up to the specific implementation. GraphQL frameworks like Relay further extend that basis by also asserting a basic set of semantics (e.g. standardising how queries should handle sorting and that every entity has a global ID).

**Cypher** is a graph query language originally written for Neo4J. Like SQL it is not well-suited for multi-model databases but it is fairly popular with people who only need to work with graph data. You only need to learn Cypher if you're going to use graph databases that only support queries with Cypher. It's not relevant for ArangoDB.

If you're going to create a GraphQL API you have to write a GraphQL schema, which defines your individual semantics (i.e. types, queries, parameters) and you have to implement that schema (i.e. define functions that can be invoked to resolve fields and queries that are part of a GraphQL request).

When implementing a GraphQL schema for ArangoDB you have two options:

1. You can implement it within ArangoDB using [the GraphQL integration for Foxx](https://docs.arangodb.com/latest/Manual/Foxx/GraphQL.html) built on [graphql-sync](https://github.com/arangodb/graphql-sync). Because Foxx runs within ArangoDB, you avoid network overhead when resolving GraphQL requests because you can directly access ArangoDB's JavaScript API instead of going over the HTTP API like arangojs does when accessing ArangoDB from Node.js.

2. You can implement it using [graphql-js](https://github.com/graphql/graphql-js) in Node.js and resolve fields by performing requests to ArangoDB using arangojs over HTTP. This is more flexible because you can scale the GraphQL API server independently of ArangoDB and don't have to touch the database if some of your fields are resolved outside the database (e.g. using external APIs like GitHub or Facebook). However requests to ArangoDB will have to touch the network and thus be slower than when using Foxx.

The reason you may want to use AQL to resolve a field in GraphQL is that some fields in GraphQL schemas do not map one-to-one to actual fields in how your data is stored in the database and exposing those implementation details is not only noisy but also very inefficient.

For example, a `friends` field on a `user` object would likely conceptually be a list of other users but in the database you might want to either store them as a list of IDs or as edge documents. Additionally you might want to filter the actual data you expose, such as by excluding banned/blocked accounts. By writing an actual query using AQL instead of just using something like `edgeCollection.outEdges` you can filter the data you retrieve from the database before it leaves the database rather than having to extract all of it and then filter out the irrelevant data (which is even more inefficient if you implement your GraphQL schema outside the database).

**Comment by dmk255** [comment]
@pluma That's a very good highlevel overview. It may be helpful to add that to the README / a wiki. I've seen a lot of people really confused about graphql and how it works with graph databases.

**Comment by webmobiles** [comment]
thanks @pluma , the problem is that I read on experts websites that more important is to learn graphql , and that suis with my case, i want to test some database like arangodb, neo4j, orientdb, titan, but not to learn an different api for every engine   just graphql because the system i need to build is not really big and complex , but need something to reemplace classic restful api,  and then work with angular4 or reactjs, with typescrip, so to learn an js library that works just with arangodb is not covenient.   Some of links i've read about graph, but for they is more important graphl and not particular libraries:

I wrote this blogger by example
https://medium.com/@frikille/moving-from-rest-to-graphql-e3650b6f5247
his reply was:
"It doesn’t matter what database you use. GraphQL is just a thin layer between the front-end and your backend business logic. I like to think about it as a switchboard: it just controls the flow to retrieve all data that was requested. The way the data is retrieved from a data store (or multiple data stores) is up to yo"

https://medium.com/@maetl/having-used-titan-neo4j-and-orientdb-both-at-work-and-on-personal-projects-over-the-past-6-3bce614d7038

**Comment by pluma** [comment]
@webmobiles they're not wrong.

You don't need to worry about the database to use GraphQL. You can put GraphQL in front of pretty much any database or 3rd party service and in fact you can put one GraphQL API in front of any combination of them. To that extent it doesn't matter what technology you use behind that, just like it doesn't for REST APIs.

However that's only half of the truth. It's "not wrong" because GraphQL in fact doesn't care about the details of the communication between wherever GraphQL terminates and where the data comes from. That's not part of GraphQL just as it isn't part of REST.

However in practice even as a frontend developer it helps to think of your application as the entire stack you're using, not just the last mile that directly concerns you. GraphQL presents a trade-off. It gives you a lot more flexibility in how you access your data in the frontend but in return this means it becomes much harder to optimise how you fetch that data in the backend. Dataloader and other tools help to combat some of that inefficiency by eliminating some redundancy but in the end it's still a trade-off and you need to be aware of that. There is no free lunch and GraphQL is not a panacea.

As for how it all comes together: in REST APIs you would write HTTP endpoints that execute server-side code when accessed from the frontend, that code in turn can do things like access the database or third-party APIs. GraphQL just replaces that REST router with a GraphQL schema. Instead of executing one function per endpoint, GraphQL executes one function per property or query. Instead of passing the request and response object to each endpoint's function, GraphQL creates a context it passes to each property as it evaluates the incoming GraphQL request.

The article from Peter Balasz you link actually shows how this is done using GraphQL: some properties have a "resolve" method, he uses Bookshelf (an ORM) to talk to the database but you could simply use AQL queries or even the arangojs API directly to implement them.

The comment by Mark Rickerby you also linked is actually more a criticism of people trying to apply ORMs (which actually solve a problem specific to how people use relational databases) than about graph databases and only tangentially related to GraphQL.
