### ISSUE TITLE
Creating API route for arangoDB 

### ISSUE THREAD

**Issue by yuvanesh10** [arangodb/arangojs#493]
I am at the beginning stage of learning the process. So far I could able to connect to the database from node server and successfully able to receive queries or id from collections and even edge collections with the help i got from here.All these were done simply by directly running the server.js file.  Now I would like to create a api route for each  individual task so that I can use this api to use with front end. I did some basic things that works fine but i dont know how to do it to access from arangoDB. I have attached my server.js file and routes.js file
Can anyone suggest me how to do it ?

## server.js ##

// BASE SETUP
// ## Assigning the values

const arangojs = require('arangojs');
const aqlQuery = arangojs.aqlQuery;
const now = Date.now();

// ## Const variables for connecting to ArangoDB database

const host = '192.000.00.000'
const port = '8529'
const username = 'xyz'
const password = 'xyz'
const path = '/_db/sgcdm_app/_api/'
const database = 'sgcdm_app'

// ## Connection to ArangoDB

db = new arangojs.Database({
    url: `http://${host}:${port}`,
    databaseName: database
});
db.useBasicAuth(username, password);

const collection = db.edgeCollection('included_in');
const edge = collection.edge('included_in/595783');

//============

//## call the packages we need

var express    = require('express');        // call express
var app        = express();                 // define our app using express
var bodyParser = require('body-parser');

//## configure app to use bodyParser()------// this will let us get the data from a POST

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

var port1 = process.env.PORT || 8080;        // set our port

require('./api/routes/routes')(app);

// START THE SERVER

app.listen(port1);
console.log('Magic happens on port1 ' + port1);

###  routes.js ####

module.exports = function(app){

  app.get('/', function(req, res) {
    res.send('Welcome to our api!\n');
  });

  app.get('/test', function(req, res) {
    res.send('happie new year!\n');
  });

}

**Comment by dothebart** [comment]
Hi, 
thats what foxx services are intended for: https://docs.arangodb.com/latest/Manual/Foxx/

**Comment by yuvanesh10** [comment]
@dothebart I didnt know that..,I will have a look right now. Thank you

**Comment by yuvanesh10** [comment]
@dothebart  I just started with the basic step got stuck..just followed the page.
""Error: Cannot find module '@arangodb/foxx/router'""

**Comment by pluma** [comment]
@yuvanesh10 Try following the tutorial at https://docs.arangodb.com/latest/Manual/Foxx/GettingStarted.html

It seems you're trying to run the Foxx code in Node.js. The idea behind Foxx is that you upload the code directly into ArangoDB to extend the ArangoDB HTTP API with your own routes. You can find more info here: https://www.arangodb.com/why-arangodb/foxx/

Note that the JS environment provided by ArangoDB is not identical with that of Node.js (you can think of ArangoDB Foxx as a built-in alternative to Node.js) so for example nothing is ever asynchronous (so no promises or timeouts/intervals are supported).

If you would rather stay in Node.js because you want to use other libraries or do more than just access ArangoDB, one option to extend the code you showed so the `db` object is available outside your server.js would be either to put it into a separate file so you can require it from both files or passing it into express with `app.set`: http://expressjs.com/en/4x/api.html#app.set

**Comment by yuvanesh10** [comment]
@pluma thank you the detailed answer. Foxx seems to be another framework. But what i am trying to do is..,I have tried to display the collections key from DB from node just by running server.js. It displays in the console. Instead of that is there any way to display the result in the browser. ?
I hope you wont mind me asking this question !!

**Comment by yuvanesh10** [comment]
@Simran-B @pluma Adding few more details to my problem. in other words..,how can i create a function to call the arangdb api.,,SO that I can call the node function in to my angular front end framework.
