### ISSUE TITLE
better way for transaction support

### ISSUE THREAD

**Issue by maku** [arangodb/arangojs#514]
For me the possibility to have transaction support is a huge selling point for ArangoDB. So I played around with transaction support and it feels rather painfull how it works (especially with more complex functions)
e.g. my code is written in typescript now I have to write a javascript function as a string.

So my question: would it be possible to provide an API e.g. like firestore (https://firebase.google.com/docs/firestore/manage-data/transactions) to handle transactions?

I know it would be possible to use foxx. But from my point of view usage of foxx further enhances the complexity of the build / testing/ tooling etc. (coding in typescript, etc) especially when the most part of data base logic is already coded in a simple nodejs backend.

**Comment by pluma** [comment]
Currently the only transaction API that ArangoDB provides is the one available in arangojs. The reason you have to pass a JavaScript function is because that is code that will be executed in the database rather than in Node. There's currently no way around this.

I'd suggest opening an issue on the [ArangoDB repository](/arangodb/arangodb) instead.

**Comment by maku** [comment]
@pluma thank you for responding. I opened an issue...
