### ISSUE TITLE
Handle rocksdb write conflict internally

### ISSUE THREAD

**Issue by gurisko** [arangodb/arangojs#523]
This is a feature request where we would repeat requests that fail due to rocksdb conflict (ERROR_ARANGO_CONFLICT).

**Comment by pluma** [comment]
Hi @gurisko,

conflicts arise when two write operations attempt to modify the same data. There is no safe way to resolve this conflict at the driver level because this creates a potential for silent data loss. Conflicts should be resolved at the application level.

The reason you're seeing write conflicts more often with RocksDB right now is that transactions are applied differently in the RocksDB storage than the MMFiles storage. The team is working on a feature that allows users to configure ArangoDB to use MMFiles-style exclusive locks in RocksDB, which will reduce the likelihood of conflicts at the cost of some performance.

You can follow the progress of that feature at this PR: https://github.com/arangodb/arangodb/pull/4091

In the meantime I suggest catching conflicts when you know the operation can be retried safely.

**Comment by rhclayto** [comment]
Are you aware of any good tutorials/blogs/etc. discussing good strategies for handling write-write conflicts application-side, especially with respect to ArangoDB/RocksDB?
