### ISSUE TITLE
Is there a way to use NPM modules in a transaction?

### ISSUE THREAD

**Issue by toymachiner62** [arangodb/arangojs#545]
I'm trying to loop through an array, check if the _key already exists, if it does generate a new one using the [uuidv4](https://www.npmjs.com/package/uuidv4) module. I'm trying to this all within a transaction. 

Is it possible to use NPM modules within transactions? If so how?

**Comment by pluma** [comment]
There are some NPM modules bundled with ArangoDB for various reasons:

https://docs.arangodb.com/3.3/Manual/Appendix/JavaScriptModules/

However generally if you need to use NPM modules you should consider using [Foxx](https://foxx.arangodb.com) instead of sending JavaScript over the wire using arangojs.

Keep in mind that the JS environment of ArangoDB is slightly different from that of Node or the browser, especially because it is entirely synchronous:

https://docs.arangodb.com/3.3/Manual/Foxx/Dependencies.html

**Comment by toymachiner62** [comment]
The whole idea of foxx services seems wrong to me. Especially when it comes to decoupling, scaling, or deploying independently from the actual arangodb. This [caveat](https://docs.arangodb.com/3.0/Manual/Foxx/Dependencies.html#compatibility-caveats) is also another reason I don't like the idea of foxx. What about choosing which version of node to use? Can that be done with foxx?

**Comment by Simran-B** [comment]
ArangoDB does not use or embed Node.js. There is only an embedded V8 and things are run blocking and multi-threaded.

Regarding "deploying independently from the actual arangodb": Why would you want to do that? Foxx is data-centric microservices, to be run close to the data instead of sending lots of data for processing to a client.
