### ISSUE TITLE
Typing errors: Cannot find name 'Blob'

### ISSUE THREAD

**Issue by sshillyer** [arangodb/arangojs#577]
I have created a minimal example project that recreates my problem:
https://github.com/sshillyer/arangojs-min-error

It involves only a couple of lines of code and only typescript and arangojs modules. I tried using @types/node in the example as well but also has the problems aforementioned.

Open to ideas! Thanks

_Originally posted by @sshillyer in https://github.com/arangodb/arangojs/issue_comments#issuecomment-434476480_

**Comment by sshillyer** [comment]
I'm sorry, I just realized for some reason you must include "dom" in tsconfig.json 'lib' array to get this type. Found answer elsewhere.

Closing.

**Comment by pluma** [comment]
The library is meant to be useful both in the browser and in Node. The browser APIs use `Blob` instead of `Buffer` (which is Node's non-standard equivalent). Sadly this means in order to support both, arangojs needs to deal with both types.

I'm trying to find out a better way to do this but for the time being this means that even if your project doesn't use any DOM APIs you need to add `dom` to your `lib`.
