### ISSUE TITLE
Collection.list() result limit is not configurable

### ISSUE THREAD

**Issue by deividasjackus** [arangodb/arangojs#581]
The current [collection.list()](https://github.com/arangodb/arangojs/blob/master/docs/Drivers/JS/Reference/Collection/DocumentManipulation.md#collectionlist) API seems to only return the first 1000 references with no option to specify a custom limit.

**Comment by Simran-B** [comment]
The HTTP endpoint is `PUT /_api/simple/all-keys`. All `/_api/simple` routes will be considered as deprecated from 3.4.0 on, which would include this particular route, but I don't know what our recommendation is to replace the call with (`/_api/cursor` with different AQL queries to emulate the _type_ option?).

**Comment by pluma** [comment]
@Simran-B that endpoint wasn't deprecated in the latest docs build unlike the other simple queries. It's also not on the simple queries page, which might mean it was overlooked.

Can you please make sure someone takes a close look at the HTTP API docs before 3.4.0 goes out the door? Currently that documentation is the authoritative reference for driver maintainers and that means it's vital that it's up to date and accurate.

**Comment by Simran-B** [comment]
It was overlooked as far as I can tell. All `/_api/simple` routes are supposed to be deprecated from v3.4.0 on, which includes `/all-keys`. I need to check if this is really intentional, but I guess so. An equivalent AQL query to the `/_api/cursor` endpoint seems superior anyway, but for the time being I guess we can leave it as it is in drivers.

If it is really limited to the first 1000 documents, then we need to add a remark to the documentation. The docs show that the response looks like `{ "results": [ ... ], "hasMore": true/false }`, which seems to indicate that this is like a cursor. Can you check if you can fetch more documents after the initial response? Could be an oversight in the JS driver.

**Comment by pluma** [comment]
@Simran-B in order to fetch more the result would need to return a cursor ID, which it apparently doesn't.

**Comment by pluma** [comment]
FYI this endpoint doesn't even guarantee a consistent order:
> Note that the results have no defined order and thus the order should not be relied on.

The result doesn't include any information suggesting there's a way to fetch the remaining result. The HTTP docs also don't indicate where the limit comes from or how it could be modified. I don't see anything directly actionable here.

**Comment by pluma** [comment]
Turns out the endpoint returns a cursor, the ID is just not set unless the result is incomplete.

The new major release will return a cursor from this method instead of simply an array of documents but it will also mark all simple query methods as deprecated for ArangoDB 3.4 and drop support for ArangoDB 2.8.
