### ISSUE TITLE
Can save documents with JavaScript Date objects but they come back serialised

### ISSUE THREAD

**Issue by lostpebble** [arangodb/arangojs#602]
For example, if I save an object like this to my collection:

```console
{
  "_key": "1000082978092769",
  "title": "Angel Williamson",
  "tags": [
    "es_bd_rea_prv",
    "es_bd_rea_age"
  ],
  "startDate": Date 2019-10-11T18:25:37.842Z {},
  "endDate":  Date 2019-10-19T20:16:30.067Z {}
}
```

I'm passing in real JavaScript Date objects for `startDate` and `endDate`.

When I query on this collection later, I'm getting an object returned with the Date objects still serialised from the database:

```json
{
  "_key": "1000030896518899",
  "title": "Nicholas Potter",
  "tags": [
    "es_qa_rat",
    "es_bd_rea",
    "es_bl_rea_adt"
  ],
  "startDate": "2019-12-23T16:28:11.057Z",
  "endDate": "2019-12-28T06:06:08.202Z"
}
```

Is there no way for us to get the real Date objects back from the query?

How I'd usually do it with `JSON.parse()` when sending dates over the wire is with a "reviver" passed in as a second argument. What is the expected way for us to do it here? To purposefully go and convert those strings to dates?

**Comment by Simran-B** [comment]
JSON doesn't support Date objects, but JSON is used in transport by ArangoDB and AQL also supports just the data types known from JSON. Therefore, your options are ISO 8601 date strings or numbers (milliseconds since Januar 1st, 1970). Also see: https://docs.arangodb.com/3.4/AQL/Functions/Date.html

Note that ArangoDB stores data in a different way internally, and is also capable of storing non-JSON data types (https://github.com/arangodb/velocypack), but as long as JSON is available as wire format it's nearly impossible to expose this functionality.

I assume that ArangoJS serializes your Date object already (`JSON.stringify(new Date())` returns an ISO string), so the backend doesn't even know about your intention. You will have to create a a new Date object from either an ISO string or a millisecond timestamp.

**Comment by lostpebble** [comment]
Thanks for the response. I assumed as much.

I guess the schema-less nature of it all also limits any kind of automatic conversion by ArangoJS when receiving documents.

I've read up on velocypack before and saw it was capable of storing information about Dates as well - so that's why I thought that maybe the library could infer this information too. As mentioned in the docs:

> covers all of JSON plus dates, integers, binary data and arbitrary precision numbers

Its a slight annoyance as it means an extra "hydration" step after every query or get. Takes a little away from the simple nature of ArangoDB overall. But not a massive issue!

**Comment by Simran-B** [comment]
With JSON you essentially send one big string over the wire and need to parse it to e.g. an object in JavaScript on the client side to work with it. The benefit is that JSON is a standard format for which there are parsers available in almost every programming language. The downside is that you can only represent a few basic data types. What can also be a problem is that JSON allows arbitrary long numbers, but not every programming language supports arbitrary long integers/decimals. Also see https://github.com/arangodb/arangodb/issues/6626

VelocyPack supports more data types and is a binary format, but it still needs to be processed on the client-side to turn something e.g. into Date object. The server can't send it as JavaScript Date object directly, because the memory representation of data structures very largely between languages and systems and may even contain references to other memory locations, which can't be predicted.

What is possible of course is to automate the process of parsing/converting what you get from the backend into the desired data structures in your client. Take a look at orango for instance:
https://github.com/roboncode/orango

While Foxx runs on the server-side, it may still go over the network internally: it is run on Coordinators node a cluster while the data is stored on DB-Server nodes. But that doesn't apply to single server instances, and to answer your question: Date objects are also serialized if you use Foxx. The interfaces it uses would need to be changed to use VelocyPack including encoding and decoding of Dates.

**Comment by pluma** [comment]
I'm closing this issue because it looks like your question has been answered. If you need any additional help on this issue, feel free to reopen it.
