### ISSUE TITLE
occasional "precondition failed" error

### ISSUE THREAD

**Issue by LJNeon** [arangodb/arangojs#650]
Every once in a while I'm getting the following error:
![image](https://user-images.githubusercontent.com/23249107/75131429-53d57980-5690-11ea-9ca4-074de7673991.png)
A quick search claims I should only receive this when I try to update a document that no longer exists, however that isn't the case here. I can simply run the update request again and it works fine, I'm 100% certain the document exists. An example of the code that throws would be:
```js
collection.update(key, {roles: {[role.id]: amount}}, {keepNull: false});
```

**Comment by pluma** [comment]
Code 1200 ("conflict") is described as "Will be raised when updating or deleting a document and a conflict has been detected" in the ArangoDB source code.

This sounds like an issue with ArangoDB, not the driver. I'm not sure in which scenarios this error is raised but is it possible there are any ongoing transactions?

Otherwise I would direct you to the ArangoDB Community Slack for further investigation: https://slack.arangodb.com/

**Comment by LJNeon** [comment]
I'm not using any transactions at all, my code has nothing but updates and upserts. I'll check out the slack, thanks.

**Comment by LJNeon** [comment]
The issue ended up being that I was calling `collection.update()` with a `key` that didn't match an existing document, adding that check has made the error vanish. Whether that's intended or a bug I wouldn't know.
