### ISSUE TITLE
domain.active is lost when using promises

### ISSUE THREAD

**Issue by Back-io** [arangodb/arangojs#66]
Happens across the entire library ... not sure if this is by design.
Specifying callback functions directly in each method call keeps the active domain intact.

**Comment by pluma** [comment]
Could you elaborate a bit?

Which of the following scenarios does it occur in:

* in a promise handler when also specifying a callback
* in a promise handler when *not* also specifying a callback
* in a callback when promises are available
* in a callback when promises are not available or explicitly disabled

If it's in the promise handler in both of the first two cases, this is probably by design -- please confirm that it's not happening in other promise-returning libraries. If it only happens in one of the first two cases, and/or only one of the last two cases, this is likely a bug in arangojs.

**Comment by pluma** [comment]
The driver will no longer return promises when a callback is specified, so if this was a bug in arangojs, it has likely been fixed. If it's a common behaviour of promises, that's likely intentional behaviour and outside of the scope of arangojs.
