### ISSUE TITLE
what is a lock timeout?

### ISSUE THREAD

**Issue by p30arena** [arangodb/arangojs#674]
Hi

Some  of my requests fail with this response:
"lock timeout"
what's the meaning of this?

**Comment by pluma** [comment]
That sounds like a question about ArangoDB rather than the driver. According to the [ArangoDB error code reference](https://www.arangodb.com/docs/3.6/appendix-error-codes.html):

> Will be raised when there’s a timeout waiting for a lock.

Here's a primer to ArangoDB locking behavior: https://www.arangodb.com/docs/3.6/transactions-locking-and-isolation.html

I'm guessing you either have a lot of concurrent transactions or some transactions involve slow queries or are otherwise slow.

For help with ArangoDB I'd recommend checking out the community slack: https://slack.arangodb.com/

**Comment by pluma** [comment]
I'm closing this ArangoDB-related question due to inactivity. Please check the community slack if you need further assistance: https://slack.arangodb.com
