### ISSUE TITLE
Cursor.count is always undefined

### ISSUE THREAD

**Issue by Kurtas** [arangodb/arangojs#73]
Hi, 

I have problem with Cursor, cursor.count should return total number of documents in the query result, but it is always undefined, even although the query has any results. There should be 0 if query don't have any result.

Using arangojs 2.14.2

```
ArrayCursor {
  extra:
   { stats:
      { writesExecuted: 0,
        writesIgnored: 0,
        scannedFull: 3,
        scannedIndex: 0,
        filtered: 2 },
     warnings: [] },
  _connection:
   Connection {
     config:
      { url: 'http://localhost:8529',
        databaseName: 'db',
        arangoVersion: 20300,
        promise: [Object],
        agentOptions: [Object],
        headers: [Object] },
     _request: [Function: request],
     promisify: [Function] },
  _api:
   Route {
     _connection:
      Connection {
        config: [Object],
        _request: [Function: request],
        promisify: [Function] },
     _path: '_api',
     _headers: undefined },
  _result:
   [ { hostname: 'RRA1',
       sn: '10.52.255.1',
       _id: 'vDevice/79116270599',
       _rev: '79116270599',
       _key: '79116270599' } ],
  _hasMore: false,
  _id: undefined,
  _index: 0,
  count: undefined }
```

**Comment by pluma** [comment]
arangojs 2.14.2 is ancient and unsupported. You should be using arangojs 3.x or the latest alpha release.

In any case, the cursor doesn't have a count property set by default. Because determining the exact number of results may be a performance issue, the API will only return the count if the `count` option is provided and set to `true`:

```js
db,query('RETURN 1', {}, {count: true})
.then(cursor => console.log(cursor.count === 1));
```

You are right that the driver can figure out the number of results if it is less than the maximum number of results, though. But you shouldn't rely on `count` being set if you're not explicitly asking for it.

**Comment by Kurtas** [comment]
Thanks for advice about opts.count param, it works now.
