### ISSUE TITLE
Collection and graph check: API request 

### ISSUE THREAD

**Issue by gitgkk** [arangodb/arangojs#753]
I'm using the pyarango and the JS drivers on my project but the APIs are not the same on the JS side.
The [https://pyarango.readthedocs.io/en/latest/database/](url) has 
- hasCollection(name)
- hasGraph(name)

both of which are very handy and create a clean code rather than using the current 

- listCollections(excludeSystem?: boolean)
- collections(excludeSystem?: boolean)
versions
Finding whether a collection exists will be much easier and straight forward.

My request is that the dev team implement an efficient version which works has the same interface and work like the pyarango api version cited above.

Thanks!

**Comment by autumnblazey** [comment]
i think for `hasCollection` you can do something like this:

```ts
db.collection("collection_name").exists();
```

not sure about `hasGraph` though

**Comment by pluma** [comment]
You can do the same for `Graph`: `await db.graph("graph_name").exists()`

**Comment by pluma** [comment]
I'm closing this as there is no significant advantage in having these aliased on the `Database` object simply because pyArango went this way. The advantage of using the `exists()` method is that you will need to perform any other operations via the `Collection` or `Graph` object anyway and there are very few scenarios where you only want to check for existence and do nothing else with that collection or graph (and in those, you can still do it as above).

Feel free to reopen if you think the API is insufficient.
