### ISSUE TITLE
[FEATURE REQUEST] Some other behavior on 404 error

### ISSUE THREAD

**Issue by amurchick** [arangodb/arangojs#94]
Sometimes we look for document and not always ready to write extra code for `404` error catching:
```
var doc = null;
try {
	doc = yield files.firstExample({filePath: filePath});
} catch (err) {
	if (!err || err.code !== 404)
		throw err;
}

// If document not exists - create it
if (!doc)
	yield createDoc({filePath: filePath});
```

It looks better, when actually document not found and no error condition - simply return `null`:
```
var doc = yield files.firstExample({filePath: filePath});

// If document not exists - create it
if (!doc)
	yield createDoc({filePath: filePath});
```

This behavior may be persistent or switched by user choice, for example:
```
var db = require('arangojs')({safe404: true});
```

Thank you!

**Comment by pluma** [comment]
This is likely out of scope for this driver. If the HTTP API considers something an error, arangojs should reflect that behaviour. The only case where arangojs intentionally deviates from the HTTP API is the cursor API.

If you find this pattern re-occuring throughout your code it should be easy enough to create a wrapper that translates 404s to nulls, e.g. something along the lines of:

```js
function safely404(fn) {
  return async function (...args) {
    try {
      return await fn(...args);
    } catch (err) {
      if (err && err.code === 404) return null;
      throw err;
    }
  };
}

let doc = await safely404(::files.firstExample)({filePath});
if (!doc) doc = await createDoc({filePath});
```

**Comment by pluma** [comment]
The design goals of this driver are to be as close to the metal as possible without sacrificing usability. The reason your request falls out of scope is that it would require either deviating from the behaviour of the HTTP API for a single use case or adding complexity.

Keep in mind that your example code is likely not something you would want to use in production: if you only want one instance of a document to exist you should either use the document's key or add a unique index. If an API miss is an expected scenario, it's also probably safer to try to save and then handle uniqueness constraint violations as a non-error (rather than checking and then creating it without allowing for a uniqueness constraint violation, meaning the code will break if another process/user/client creates the same document in between the HTTP calls).
